version: '3.8'

services:
  db:
    container_name: flowaisystem-db
    image: postgres:16
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_DB:   flowaidb
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes: 
      - flowai_pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  web:
    build:
      context: .
    continer_name: flowaisystem-web
    depends_on:
      db:
        condition: service_started
    environment:
        ASPNETCORE_ENVIRONMENT: Production
        ConnectionStrings__DefaultConnection: Host=db;Port=5432;Database=flowaidb;Username=postgres;Password=${DB_PASSWORD}
        Jwt__Key: ${JWT_KEY}
        Jwt__Issuer: FlowAISystem
        Jwt__Audience: FlowAISystemUsers
    image: flowaisystem
    ports:
      - "8080:8080"
    restart: unless-stopped
volumes:  
  flowai_pgdata: